services:
  api:
    build: 
      context: ./Core
    container_name: tinyurl_api

    depends_on:
      - mongo
      - redis
    environment:
      MONGO_URL: mongodb://mongo:27017
      Secret_Key: "xyz"
      REDIS_URL: redis://redis:6379

  mongo:
    image: mongo:8
    container_name: tinyurl_mongo

    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7
    container_name: tinyurl_redis

  
  frontend:
    build:
      context: .
      dockerfile: React/Dockerfile
    container_name: tinyurl_api_frontend
  nginx:
    build:
      context: ./nginx
    ports:
     - "80:80"
    container_name: tinyurl_api_nginx
    depends_on:
     - frontend
     - api
volumes:
  mongo_data: