services:
  api:
    build: .
    container_name: tinyurl_api
    ports:
      - "8000:8000"
    depends_on:
      - mongo
      - redis
    environment:
      MONGO_URL: mongodb://mongo:27017
      Secret_Key: "xyz"
      REDIS_URL: redis://redis:6379

  mongo:
    image: mongo:8
    container_name: tinyurl_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7
    container_name: tinyurl_redis
    ports:
      - "6379:6379"

volumes:
  mongo_data: